"""ChromaDB persistence layer for Developer Memory.

Spec §9 — idempotency contract (3-case upsert):
  1. New document (id not in collection)  → embed + add to collection
  2. Exact duplicate (same id + same file_path AND repo_url) → skip (no-op)
  3. File moved (same id but different file_path or repo_url) → metadata-only update;
     no re-embedding (content is identical — the SHA-256 proves it)

ChromaDB metadata values must be str | int | float | bool. list[str] fields (tech_stack)
are stored as JSON strings and deserialized by _unpack_*_results() before returning to callers.
"""

import json
import logging
from collections.abc import Callable
from urllib.parse import urlparse

import chromadb

from src.config.settings import Settings
from src.ingest.embeddings import get_embeddings
from src.models.chunk import SummarizedChunk, UpsertResult

logger = logging.getLogger(__name__)


class ChromaLibrarianClient:
    """Persistent ChromaDB client for Developer Memory ingest and retrieval.

    All write operations use SHA-256 content_hash as the document id for idempotency.
    Embeddings are generated by OllamaEmbeddings (mxbai-embed-large) unless an
    alternative embedding_fn is injected (used in tests to avoid live Ollama calls).

    Args:
        client: chromadb.ClientAPI instance. If None, creates a client from Settings
            (HttpClient when chroma_host is set, PersistentClient otherwise).
            Inject chromadb.EphemeralClient() in tests.
        embedding_fn: Callable[[list[str]], list[list[float]]] for embedding generation.
            If None, uses get_embeddings().embed_documents (OllamaEmbeddings at startup).
        collection_name: ChromaDB collection name. If None, reads from Settings
            (CHROMA_COLLECTION env var). Pass explicitly for multi-tenant deployments,
            versioned schema migrations, or test isolation with EphemeralClient.
        settings: Settings instance for Chroma connection config. If None, constructs
            Settings() from the environment. Pass Settings(chroma_host="") in tests
            to use local mode without env mutation or monkeypatching.
    """

    def __init__(
        self,
        client: chromadb.ClientAPI | None = None,
        embedding_fn: Callable[[list[str]], list[list[float]]] | None = None,
        collection_name: str | None = None,
        settings: Settings | None = None,
    ) -> None:
        # F6: URL-parse logic lives here (once). Settings owns the raw env values;
        # ChromaLibrarianClient converts them to a chromadb.ClientAPI — no other
        # caller should read CHROMA_HOST or CHROMA_DATA_PATH from os.environ.
        cfg = settings or Settings()
        if client is None:
            if cfg.chroma_host:
                # Docker / network deployment: CHROMA_HOST is a full URL (http://chromadb:8000).
                # HttpClient expects hostname and port separately — parse from the validated URL.
                # Settings._validate_chroma_host() guarantees scheme is http/https and hostname
                # is non-empty, so parsed.hostname will never be None here.
                parsed = urlparse(cfg.chroma_host)
                client = chromadb.HttpClient(
                    host=parsed.hostname or "localhost",
                    port=parsed.port or 8000,
                )
            else:
                # Local development: chroma_host empty → persist to chroma_data_path.
                client = chromadb.PersistentClient(path=cfg.chroma_data_path)
        # Connect and create/fetch the collection. Wrapped to surface a clear
        # actionable message rather than a raw chromadb protocol error.
        try:
            self._collection = client.get_or_create_collection(
                name=collection_name or cfg.chroma_collection,
                metadata={"hnsw:space": "cosine"},
            )
        except Exception as exc:
            raise RuntimeError(
                f"ChromaDB connection failed (CHROMA_HOST={cfg.chroma_host or 'unset'}). "
                "Ensure the chromadb service is running and the client/server versions match. "
                f"Original error: {type(exc).__name__}: {str(exc)[:200]}"
            ) from exc
        # Bind embedding function — injected for tests, resolved from get_embeddings() in prod.
        # get_embeddings() is not called here to avoid Ollama connection attempt at import time.
        self._embed: Callable[[list[str]], list[list[float]]] = (
            embedding_fn if embedding_fn is not None else get_embeddings().embed_documents
        )

    def exists(self, chunk_id: str) -> bool:
        """Return True if a document with this SHA-256 content_hash is already indexed.

        Used by summarize_and_upsert for the skip-before-LLM fast path: if the chunk
        is already in ChromaDB, skip the LLM summarization call entirely.

        Args:
            chunk_id: SHA-256 hex string of chunk content (content_hash).

        Returns:
            True if the document exists in the collection; False otherwise.
            Returns False on any ChromaDB error (safe default — triggers re-index).
        """
        try:
            result = self._collection.get(ids=[chunk_id])
            return bool(result["ids"])
        except Exception as exc:
            logger.warning(
                "exists() check failed [%s]: %s — treating as not found",
                type(exc).__name__,
                str(exc)[:120],
            )
            return False

    def upsert_chunk(self, chunk: SummarizedChunk, meta: dict) -> UpsertResult:
        """Idempotent upsert by content_hash — implements the 3-case contract from spec §9.

        Case 1 (new): id absent in collection → embed content and add document.
        Case 2 (exact duplicate): id present, same file_path + repo_url → skip; no-op.
        Case 3 (file moved): id present, different file_path or repo_url → metadata-only
            update via collection.update(); embedding unchanged (SHA-256 proves identical content).

        Args:
            chunk: SummarizedChunk whose content_hash is used as the ChromaDB document id.
            meta: Extra metadata dict — expected keys: repo_url, branch, commit_sha, indexed_at.

        Returns:
            UpsertResult with action "inserted" | "skipped" | "updated" | "error".
        """
        chunk_id = chunk.content_hash
        # Build the full metadata record — tech_stack serialized to JSON (ChromaDB scalar constraint)
        metadata: dict = {
            "intent_summary": chunk.intent_summary,
            "tech_stack": json.dumps(chunk.tech_stack),
            "semantic_type": chunk.semantic_type,
            "key_identifiers": json.dumps(chunk.key_identifiers),
            "author_identity": chunk.author_identity,
            "file_path": chunk.path,
            **meta,
        }

        try:
            existing = self._collection.get(ids=[chunk_id])
            if existing["ids"]:
                existing_meta = existing["metadatas"][0]
                if (
                    existing_meta.get("file_path") == chunk.path
                    and existing_meta.get("repo_url") == meta.get("repo_url")
                ):
                    # Case 2: true duplicate — no work needed
                    logger.debug(
                        "upsert_chunk: skip (duplicate) id=%.8s path=%s", chunk_id, chunk.path
                    )
                    return UpsertResult(
                        content_hash=chunk_id, file_path=chunk.path, action="skipped"
                    )
                else:
                    # Case 3: file moved / repo changed — update metadata only; content unchanged
                    self._collection.update(ids=[chunk_id], metadatas=[metadata])
                    logger.debug(
                        "upsert_chunk: updated (file moved) id=%.8s path=%s", chunk_id, chunk.path
                    )
                    return UpsertResult(
                        content_hash=chunk_id, file_path=chunk.path, action="updated"
                    )
            else:
                # Case 1: new document — embed enriched text so that intent_summary
                # and key_identifiers are searchable by embedding similarity, not just
                # stored as metadata. Raw content is still the stored document for retrieval.
                identifiers_str = " ".join(chunk.key_identifiers)
                embed_text = (
                    f"{chunk.intent_summary}\n{identifiers_str}\n{chunk.content}"
                    if chunk.intent_summary or identifiers_str
                    else chunk.content
                )
                embeddings = self._embed([embed_text])
                self._collection.add(
                    ids=[chunk_id],
                    documents=[chunk.content],
                    embeddings=embeddings,
                    metadatas=[metadata],
                )
                logger.debug(
                    "upsert_chunk: inserted id=%.8s path=%s", chunk_id, chunk.path
                )
                return UpsertResult(
                    content_hash=chunk_id, file_path=chunk.path, action="inserted"
                )
        except Exception as exc:
            logger.error(
                "upsert_chunk failed [%s]: %s", type(exc).__name__, str(exc)[:200]
            )
            return UpsertResult(
                content_hash=chunk_id,
                file_path=chunk.path,
                action="error",
                error=str(exc)[:200],
            )

    def query(
        self,
        text: str,
        tech_filter: list[str] | None = None,
        where: dict | None = None,
        n_results: int = 10,
    ) -> list[dict]:
        """Semantic search with optional metadata filters.

        tech_filter is applied post-retrieval (ChromaDB has no array-contains operator on
        JSON-serialized fields). When tech_filter is set, the full collection is fetched
        before filtering — this guarantees relevant chunks are not lost due to ranking
        cutoffs (ChromaDB cannot pre-filter JSON-serialized array fields like tech_stack).

        Args:
            text: Query text to embed and search against.
            tech_filter: Optional list of tech stack terms. Returns only docs where ALL
                terms appear in tech_stack (AND semantics). Applied post-retrieval in Python.
                Triggers a full-collection fetch to ensure no relevant chunks are missed.
            where: Optional ChromaDB where= dict for scalar metadata filtering
                (e.g., {"semantic_type": {"$eq": "Logic"}}). Passed directly to ChromaDB.
            n_results: Maximum results to return after tech_filter applied.

        Returns:
            List of result dicts with keys: id, document, metadata (tech_stack deserialized),
            distance. Empty list when collection has no documents.
        """
        if self._collection.count() == 0:
            return []

        # When tech_filter is active: fetch the entire collection so that post-filter
        # ranking is over all candidates, not just the top-N by embedding distance.
        # Without this, relevant chunks ranked beyond n_results are silently dropped.
        fetch_n = self._collection.count() if tech_filter else n_results

        query_embeddings = self._embed([text])
        kwargs: dict = {
            "query_embeddings": query_embeddings,
            "n_results": fetch_n,
            "include": ["documents", "metadatas", "distances"],
        }
        if where:
            kwargs["where"] = where

        raw = self._collection.query(**kwargs)
        rows = self._unpack_query_results(raw)

        if tech_filter:
            # tech_stack is already deserialized to list[str] by _unpack_query_results
            rows = [
                r
                for r in rows
                if all(term in r["metadata"].get("tech_stack", []) for term in tech_filter)
            ]
            rows = rows[:n_results]

        return rows

    def get_by_author(self, author_identity: str) -> list[dict]:
        """Retrieve all documents indexed for a specific author_identity.

        Args:
            author_identity: Exact string to match against ChromaDB author_identity metadata.

        Returns:
            List of result dicts. Empty list if no documents exist for this author.
        """
        results = self._collection.get(
            where={"author_identity": {"$eq": author_identity}},
            include=["documents", "metadatas"],
        )
        return self._unpack_get_results(results)

    def get_distinct_tech_stack(self) -> list[str]:
        """Return the unique tech_stack labels present in the collection.

        Scans all metadata records and unions the deserialized tech_stack arrays.
        The result is the ground-truth set of technology labels actually indexed —
        used by semantic_searcher to build a dynamic alias lookup rather than
        maintaining a static allowlist.

        Returns:
            Sorted list of distinct tech label strings. Empty list if the collection
            has no documents or on any ChromaDB error (safe default — callers fall
            back to no filter).
        """
        if self._collection.count() == 0:
            return []
        try:
            results = self._collection.get(include=["metadatas"])
            distinct: set[str] = set()
            for meta in results.get("metadatas") or []:
                raw = meta.get("tech_stack")
                if raw:
                    distinct.update(json.loads(raw))
            return sorted(distinct)
        except Exception as exc:
            logger.warning(
                "get_distinct_tech_stack failed [%s]: %s — returning empty list",
                type(exc).__name__,
                str(exc)[:120],
            )
            return []

    def get_distinct_project_prefixes(self) -> dict[str, str]:
        """Return a mapping of project name → file_path prefix for all indexed projects.

        Scans file_path metadata and groups by the first two path segments
        (e.g. `projects/Chatbot_DataPipeline` → prefix `projects/Chatbot_DataPipeline/`).
        Works regardless of the top-level directory name, so repos from different
        GitHub organisations or with different root conventions are all handled.

        Returns:
            Dict mapping project name (last segment of prefix) → full path prefix
            string ending with `/`. Empty dict on no documents or any ChromaDB error
            (safe default — callers fall back to no filter).

        Example:
            {"Chatbot_DataPipeline": "projects/Chatbot_DataPipeline/",
             "Geoportugal": "projects/Geoportugal/",
             "hr_assistant": "projects/hr_assistant/"}
        """
        if self._collection.count() == 0:
            return {}
        try:
            results = self._collection.get(include=["metadatas"])
            prefixes: dict[str, str] = {}
            for meta in results.get("metadatas") or []:
                path = meta.get("file_path", "")
                parts = path.split("/")
                # Need at least root/ProjectName/file to extract a meaningful project
                if len(parts) >= 3:
                    project_name = parts[1]
                    prefix = f"{parts[0]}/{parts[1]}/"
                    prefixes[project_name] = prefix
            return prefixes
        except Exception as exc:
            logger.warning(
                "get_distinct_project_prefixes failed [%s]: %s — returning empty dict",
                type(exc).__name__,
                str(exc)[:120],
            )
            return {}

    def get_quarantined(self) -> list[dict]:
        """Retrieve all documents with semantic_type == 'quarantine'.

        Used by Streamlit Command Center to populate the PII Review Queue panel.

        Returns:
            List of quarantined result dicts. Empty list if none exist.
        """
        results = self._collection.get(
            where={"semantic_type": {"$eq": "quarantine"}},
            include=["documents", "metadatas"],
        )
        return self._unpack_get_results(results)

    def release_quarantine_item(self, doc_id: str) -> bool:
        """Update a quarantined doc's semantic_type from 'quarantine' to 'reviewed'.

        Uses get-then-update pattern because ChromaDB collection.update() replaces the
        entire metadata dict — a direct update without a prior get would silently delete
        all existing metadata fields (file_path, tech_stack, indexed_at, etc.).

        Args:
            doc_id: ChromaDB document ID to release from quarantine.

        Returns:
            True if the document was found and updated; False if doc_id not found.
        """
        result = self._collection.get(ids=[doc_id], include=["metadatas"])
        ids = result.get("ids") or []
        if not ids:
            return False
        # Merge: copy all existing metadata, then update only semantic_type.
        # This preserves file_path, tech_stack, quarantine_reason, indexed_at, etc.
        meta = dict((result.get("metadatas") or [{}])[0])
        meta["semantic_type"] = "reviewed"
        self._collection.update(ids=[doc_id], metadatas=[meta])
        return True

    def get_indexed_repo_metadata(self) -> dict[str, str]:
        """Return repo_url, branch, and commit_sha from an arbitrary indexed document.

        Uses collection.get() with limit=1 (no embedding call). Valid for single-repo
        deployments where all chunks share the same repo_url, branch, and commit_sha.
        Returns empty dict when the collection has no documents or on ChromaDB error —
        the caller (skills_cache_guard) treats empty dict as a cache miss → full synthesis.

        Note: Does NOT guarantee the most-recently-indexed document. For single-repo use,
        any chunk's metadata is authoritative. If multi-repo support is added in future,
        this method will need a where={"repo_url": ...} filter — currently out of scope.

        Returns:
            Dict with keys 'repo_url', 'branch', 'commit_sha' (all str).
            Empty dict on empty collection or ChromaDB error.
        """
        if self._collection.count() == 0:
            return {}
        try:
            result = self._collection.get(limit=1, include=["metadatas"])
            metadatas = result.get("metadatas") or []
            if not metadatas:
                return {}
            meta = metadatas[0]
            return {
                "repo_url": meta.get("repo_url", ""),
                "branch": meta.get("branch", ""),
                "commit_sha": meta.get("commit_sha", ""),
            }
        except Exception as exc:
            logger.warning(
                "get_indexed_repo_metadata failed [%s]: %s",
                type(exc).__name__,
                str(exc)[:200],
            )
            return {}

    @staticmethod
    def _unpack_query_results(results: dict) -> list[dict]:
        """Flatten ChromaDB query() nested lists into a list of result dicts.

        ChromaDB query() returns {'ids': [[...]], 'documents': [[...]], ...} — one inner
        list per query vector. We always send exactly one query vector, so index [0].
        tech_stack is deserialized from JSON string back to list[str].
        """
        rows = []
        ids = results.get("ids", [[]])[0]
        documents = (results.get("documents") or [[]])[0]
        metadatas = (results.get("metadatas") or [[]])[0]
        distances = (results.get("distances") or [[]])[0]
        for i, doc_id in enumerate(ids):
            meta = dict(metadatas[i]) if i < len(metadatas) else {}
            if "tech_stack" in meta:
                meta["tech_stack"] = json.loads(meta["tech_stack"])
            rows.append(
                {
                    "id": doc_id,
                    "document": documents[i] if i < len(documents) else "",
                    "metadata": meta,
                    "distance": distances[i] if i < len(distances) else None,
                }
            )
        return rows

    @staticmethod
    def _unpack_get_results(results: dict) -> list[dict]:
        """Flatten ChromaDB get() results into a list of result dicts.

        ChromaDB get() returns flat lists (not nested). tech_stack deserialized from JSON.
        """
        rows = []
        ids = results.get("ids") or []
        documents = results.get("documents") or []
        metadatas = results.get("metadatas") or []
        for i, doc_id in enumerate(ids):
            meta = dict(metadatas[i]) if i < len(metadatas) else {}
            if "tech_stack" in meta:
                meta["tech_stack"] = json.loads(meta["tech_stack"])
            rows.append(
                {
                    "id": doc_id,
                    "document": documents[i] if i < len(documents) else "",
                    "metadata": meta,
                }
            )
        return rows
