"""Initial migration

Revision ID: 0ae3640658aa
Revises:
Create Date: 2025-08-21 22:35:56.521146

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ae3640658aa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "districts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_districts_id"), "districts", ["id"], unique=False)
    op.create_index(op.f("ix_districts_name"), "districts", ["name"], unique=False)
    op.create_table(
        "municipalities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("area", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_municipalities_district_id"),
        "municipalities",
        ["district_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_municipalities_id"), "municipalities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_municipalities_name"), "municipalities", ["name"], unique=False
    )
    op.create_table(
        "localities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("municipality_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("feature_type", sa.String(length=50), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipalities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_localities_coordinates",
        "localities",
        ["latitude", "longitude"],
        unique=False,
    )
    op.create_index("idx_search_name", "localities", ["name"], unique=False)
    op.create_index(op.f("ix_localities_id"), "localities", ["id"], unique=False)
    op.create_index(
        op.f("ix_localities_municipality_id"),
        "localities",
        ["municipality_id"],
        unique=False,
    )
    op.create_index(op.f("ix_localities_name"), "localities", ["name"], unique=False)
    op.create_table(
        "alternate_names",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("locality_id", sa.Integer(), nullable=False),
        sa.Column("location_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("is_preferred", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["locality_id"],
            ["localities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alternate_names_id"), "alternate_names", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_alternate_names_locality_id"),
        "alternate_names",
        ["locality_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alternate_names_name"), "alternate_names", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alternate_names_name"), table_name="alternate_names")
    op.drop_index(op.f("ix_alternate_names_locality_id"), table_name="alternate_names")
    op.drop_index(op.f("ix_alternate_names_id"), table_name="alternate_names")
    op.drop_table("alternate_names")
    op.drop_index(op.f("ix_localities_name"), table_name="localities")
    op.drop_index(op.f("ix_localities_municipality_id"), table_name="localities")
    op.drop_index(op.f("ix_localities_id"), table_name="localities")
    op.drop_index("idx_search_name", table_name="localities")
    op.drop_index("idx_localities_coordinates", table_name="localities")
    op.drop_table("localities")
    op.drop_index(op.f("ix_municipalities_name"), table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_id"), table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_district_id"), table_name="municipalities")
    op.drop_table("municipalities")
    op.drop_index(op.f("ix_districts_name"), table_name="districts")
    op.drop_index(op.f("ix_districts_id"), table_name="districts")
    op.drop_table("districts")
    # ### end Alembic commands ###
